### ISSUE TITLE
changed_fields are not passed to the callback.

### ISSUE THREAD

**Issue by gghildyal** [soynatan/django-easy-audit#111]
I want to make a decision on whether to audit log or not based on whether something changed. Like omit anything that's auto updated by the model (models inheriting from TimeStampedModel for instance). The code calculates the changed_fields for updates but doesn't pass it to the callback.

**Comment by gghildyal** [comment]
I have created a PR for this - https://github.com/soynatan/django-easy-audit/pull/112

**Comment by gghildyal** [comment]
This will be addressed by https://github.com/soynatan/django-easy-audit/pull/106

**Comment by jheld** [comment]
PR #106 has been merged and released. Open to discussing in case we want to change the flow a bit, but closing for now.
