### ISSUE TITLE
object_id field is not indexed.

### ISSUE THREAD

**Issue by gghildyal** [soynatan/django-easy-audit#114]
The object_id field is not indexed which means if I have to look up what has changed till date for a given object, the query won't be as performant as it should be.

**Comment by jheld** [comment]
We have a composite index on content_type and object_id. You will need the content_type in order to be guaranteed to be looking up the correct object's info each time. It should be quite fast if you query the 2 fields together.

Does this solve your problem?

We could update the docs around this.

**Comment by gghildyal** [comment]
Ah, I missed the model Meta code `index_together = ['object_id', 'content_type', ]`. That would serve my purpose.

Thanks for the prompt reply.
