### ISSUE TITLE
the middle ware only audit authentifications

### ISSUE THREAD

**Issue by mehdiselbi** [soynatan/django-easy-audit#125]
Hi all,
I just installed the middleware in my app it's working for request and logging but it does not register any objects CRUD events when I make a change the only thing audited is the las logging for the user!
I've added
`DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True` 
but it's still not working!

**Comment by jheld** [comment]
Hello! Can you add a `easyaudit` logger to your logging config? My hunch is that we are having trouble serializing many of your changes.

**Comment by mehdiselbi** [comment]
> Hello! Can you add a `easyaudit` logger to your logging config? My hunch is that we are having trouble serializing many of your changes.
hello, @jheld  thanks for your response!  where can I find the logging config and how can I add easyaudit to it?

**Comment by jheld** [comment]
Sure.

I can try to provide something more concrete, but here's an example provided by django: https://docs.djangoproject.com/en/2.2/topics/logging/#examples

If that ends up being confusing or not working, let me know.

**Comment by mehdiselbi** [comment]
I still can't figure it out, I've never worked with loggers before and I can't even know where should I add logging config or how to do it for this middleware :/

**Comment by jheld** [comment]
Sure! Please put it in your `settings.py`
Here is one you might try to use:
```python
LOGGING = {
    "version": 1,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s log:%(name)s "
            "%(funcName)s %(module)s %(lineno)d %(message)s"
        }
    },
    "handlers": {
        "stream": {"level": "DEBUG", "class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "loggers": {
        "easyaudit": {"handlers": ["stream"], "level": "DEBUG", "propagate": True},
    }
}
```

**Comment by mehdiselbi** [comment]
I'm not lucky to use it I think :'( I just discovered that it doesn't handle CharField primary keys, even though I changed the  `object_id =IntegerField()` to `object_id = models.CharField(max_length=255)` in easy-audit models.py

**Comment by jheld** [comment]
Right.

We would like to improve the data type variety. Not sure how to do it (maybe charfield is the best approach). I imagine we would like to support type cast/coercion too. So we haven't yet.

Sorry the debug took so long.

If you did change the type make sure you also make and run a migration. But yes please do not do that for real.

I think there is an open issue for changing the type.

**Comment by mehdiselbi** [comment]
Thanks for your help, I'll try to run the migration and see if it works.

**Comment by mehdiselbi** [comment]
it works after running the migration for all the models and easy-audits migration too! Thanks a lot @jheld <3

**Comment by jheld** [comment]
you bet!

my advice for now is to have you use your adjustment, but reverse your migration once we merge the official fix in. that or fake our official one if you don't want to "reverse" yours explicitly.
