### ISSUE TITLE
Feature Request: Allow exporting of event data to a log aggregator like StatsD

### ISSUE THREAD

**Issue by ArionMiles** [soynatan/django-easy-audit#126]
It'd be nice to have the ability to pull the events data from an endpoint and pipe it to Grafana to create interesting analytics dashboards.

There's lots of options like pushing to StatsD, or a Prometheus server, maybe Graphite?

Let me know what you think :D

**Comment by ArionMiles** [comment]
Oh, just took a look at https://github.com/soynatan/django-easy-audit/pull/124

It seems to be aiming to do what I want. I'm keeping this open for now anyway to hear more ideas. If the above PR satisfies my usecase, I'll be happy to close this

**Comment by jheld** [comment]
@ArionMiles the beta 2 release of `1.2.2` (`1.2.2b2`) is now on PyPI and includes that PR so you can leverage alternative (or multiple even) backends as your project desires.

The official release will likely be closer to the end of February once we've determined stability and assuming no further changes to the release come in.

**Comment by jheld** [comment]
Please re-open (or ask me if you cannot) this issue if you find the feature on `1.2.2b2` does not work how you'd like it to, or if you think the project needs adjustments or further extended support for your use case.

Bugs related to that feature should be their own issue though.
