### ISSUE TITLE
Presave signal fails when using UUID field as PK

### ISSUE THREAD

**Issue by thommor** [soynatan/django-easy-audit#131]
The pre_save signal fails when a model uses a UUID field as a primary key.

It seems that by the time the pre_save runs the UUID field already has a value meaning the easy audit thinks it is an update and tries to retrieve the original model from the database, which fails.

```
class Customer(ExportModelOperationsMixin('customer'), models.Model):
    """Model that represents a customer"""
    id = models.UUIDField(verbose_name='ID', primary_key=True, default=uuid.uuid4, editable=False, unique=True,
                          help_text='A UUID string identifying this customer')
    """The unique UUID of this :class:`Customer`"""
```

I think this is due to the fact that the UUID field has a default but this is required for UUID fields

**Comment by nshmn** [comment]
I encountered a similar issue when trying to profile my project with django-silk.
Silk logs request with an UUID as id/pk in a varchar field and easy audit tries to store them in an integer field. I got rid of that error with changing the data type of the object_id the field to varchar BUT I didn't check if that causes other problems somewhere else, so be careful!

**Comment by thommor** [comment]
Yes I came to the same conclusion.

Im looking into other packages for the time being until a time non-integer PKs are supported

**Comment by nshmn** [comment]
https://github.com/soynatan/django-easy-audit/pull/103

I just saw that there is already a pull request addressing this.
