### ISSUE TITLE
Request Event Instability

### ISSUE THREAD

**Issue by steverecio** [soynatan/django-easy-audit#142]
Is anyone running master in a system with many concurrent users? I'm seeing some instability in that the request events don't seem to always point to the correct user when multiple users are accessing the site.

**Comment by jheld** [comment]
We run via uwsgi, so multi-process. Any thread local issues (e.g. runserver) should be taken care of by the user being stored on the thread local.

We haven't noticed any issue that you are indicating (although we haven't been watching for it).

Would you be willing to share more details about your system/runtime/configuration?

**Comment by steverecio** [comment]
I'm running gunicorn. I wasn't seeing this issue previously while running easyaudit v1.1. I recently switched to @jsoa's branch to fix my charfield pk issue and afterwards started seeing this problem so not sure if the issue came from that branch or master.

**Comment by jheld** [comment]
The charfield is only for crudevent right?

But at any rate if he can rebase against a newer version that would be ideal.

I'm not sure how quickly we'll merge the charfield fix.

**Comment by steverecio** [comment]
Yeah I don't see any reason to attribute it to the charfield code. I was previously on 1.1 and upgraded to the charfield fix to stop the incessant errors I was getting (I use a lot of guid pk's).

I realized I also switched to cloudflare at the same time so I'm currently rolling that back to help me isolate the root cause. I had no issue with this previously on 1.1 and it looks like the threading code hasn't changed in some time so I suspect it might be CF. I'll report back soon when I have more data.

**Comment by steverecio** [comment]
I've isolated the breaking change to this commit: https://github.com/soynatan/django-easy-audit/commit/57a52ae2728cb845e33905b9f03cf721ea098a2c

**Comment by jheld** [comment]
Oh that's super recent.

I assumed that current user function was thread local. It isn't?

**Comment by jheld** [comment]
https://github.com/soynatan/django-easy-audit/pull/136

**Comment by steverecio** [comment]
I haven't dug into the issue too deeply but I know that reverting that commit in the latest alpha fixes my issue. Whatever system is used to determine the current user should probably be consistent among all signal handlers.

**Comment by jheld** [comment]
Yeah this is the implementation logic:
```
def get_current_request():
    return getattr(_thread_locals, 'request', None)

def get_current_user():
    request = get_current_request()
    if request:
        return getattr(request, 'user', None)
```

so, doesn't make sense to me why that would break anything since this same function is used in the `model_signals`, too.

Should we decide that we don't have the bandwidth to fix this (or find out it was something else in the same commit), we'll remove the line which tries to access the current user (comment it and say why), so we have a breadcrumb in the future.

**Comment by steverecio** [comment]
Is the subsequent cookie / session logic definitely thread-safe? I was seeing about 80% of requests accurately tagged to the correct user but the rest seemed to be randomized by whoever was accessing the API (logged in requests and not).

**Comment by steverecio** [comment]
Also, why is the test case in the commit testing the CRUDEvent instead of the RequestEvent? Isn't it the request event logic that is being modified?

**Comment by jheld** [comment]
Eesh. I know I reviewed it, but I don't remember if I fully read through the test case. I know the test passed, but I may have just been like "great" rather than looking at the code change. The only thing he added after the implementation was the test case (at my request, make my own problems).

**Comment by jheld** [comment]
@steverecio as far as the cookie/session logic, it's been that way for years (unless there's been some other change, but I'm not aware of it).

**Comment by steverecio** [comment]
Fair enough. I have a staging environment I could use but there's no live traffic on it so it's a little harder to test. I'm currently using a local fork of the object_id branch with this commit reverted. I mainly upgraded to fix the charfield errors I was getting (which were eating into my error reporting tool quotas). I can try playing around with it more when I get some free time but I have my issue solved for now using my local fork.

**Comment by jheld** [comment]
i'm going to keep this issue open until after I semi-remove the added get user call. I will fix/adjust the test case since (long-term) it should be testing the more appropriate model type. i'm sure it was copy/paste.

**Comment by jheld** [comment]
I've "rolled" the change back (mostly commented out and put in comments and skipped the test). Hoping to put it back someday, but lowering the priority short-term.

`1.2.3a4` is now on PyPI (really is just the reversion). @steverecio if you are able to run your tests again I hope you'll find that the instability is gone. If it's not, we have a whole other set of problems!

I do want to apologize because I had forgotten to create a `1.2.3a1` for just the initial commit for the request user (which is rolled back), but I could have added it to the readme changelog for the a1. That doesn't help when people are trying to see exactly what's included in a release (even an alpha). This is atypical of me and I'll try to do better!

**Comment by jheld** [comment]
@steverecio would you mind retesting?

**Comment by jheld** [comment]
Closing since we have rolled back the likely offending code change. We can re-open/make new if it continues.
