### ISSUE TITLE
easyaudit_requestevent_url_37d1b8c4 migration drop logic breaks MySQL

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#148]
@steverecio looks like #144 breaks for MySQL; I may be able to get to it but not sure if I can do it in the next couple of days. Django may have some support for checking which kind of database is in use, and that's probably the quickest way around this (for MySQL), while keeping it working for Postgres & SQLite.

Unfortunately my project does use MySQL so although this can be merged, other projects would likely start breaking at least in their tests runs, if not on their actual new projects (should those happen).

this is against 1.2.3a4 though it was introduced in 1.2.3a3.

**Comment by steverecio** [comment]
Fixed in #149
