### ISSUE TITLE
could not save CRUDEvent.object_id as uuid

### ISSUE THREAD

**Issue by xtao-chwy** [soynatan/django-easy-audit#158]
Hello, I recently started trying easyaudit and noticed an issue when implementing with the following code:
```
crud_event = audit_logger.crud({
                                'event_type': event_type,
                                'object_repr': str(instance),
                                'object_json_repr': object_json_repr,
                                'content_type_id': c_t.id,
                                'object_id': instance.pk,
                                'user_id': getattr(user, 'id', None),
                                'datetime': timezone.now(),
                                'user_pk_as_string': str(user.pk) if user else user
                            })
```
Here I noticed the object_id is `instance.pk` and it can only be saved as an integer. However, in my case the object.pk is UUID. I saw in the code there is already a note with intend to make this field more flexible:

easyaudit.models.CRUDEvent
```
object_id = models.IntegerField()  # we should try to allow other ID types
```
Can I ask will this field be updated? If so, when it may likely to be? Thanks.

**Comment by jheld** [comment]
Hi @xtao-chwy thanks for your interest in the project. I think `1.3.0a5` will solve this for you. I think a1 might have been when it was merged. We're not planning to merge anything else, just get a little more feedback from the community and then I'll release `1.3.0` officially.

If there _is_ still a bug, please let us know, happy to help/fix and then make the release.

**Comment by xtao-chwy** [comment]
Thank you!
