### ISSUE TITLE
REMOTE_ADDR_HEADER KeyError

### ISSUE THREAD

**Issue by steverecio** [soynatan/django-easy-audit#167]
KeyError is thrown from REMOTE_ADDR_HEADER lookup. Failed lookup should probably log a warning instead of causing a blocking 500 error on the request. Tested on 1.3.0 release. I've also verified that the request is receiving the "X-Forwarded-For" header so I know its present in the request.

```
Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
django_1        |     return self.application(environ, start_response)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 139, in __call__
django_1        |     signals.request_started.send(sender=self.__class__, environ=environ)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
django_1        |     for receiver in self._live_receivers(sender)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
django_1        |     for receiver in self._live_receivers(sender)
django_1        |   File "/usr/local/lib/python3.6/site-packages/easyaudit/signals/request_signals.py", line 44, in request_started_handler
django_1        |     remote_ip = environ[REMOTE_ADDR_HEADER]
django_1        | KeyError: 'X-Forwarded-For'
```

**Comment by steverecio** [comment]
Also worth noting that the request actually does have the `X-Forwarded-For` header being sent.

**Comment by steverecio** [comment]
DJANGO_EASY_AUDIT_REMOTE_ADDR_HEADER = 'HTTP_X_FORWARDED_FOR'

**Comment by steverecio** [comment]
Re-opening this because the request will still fail if the `X-Forwarded-For` header is not sent along. This can cause errors with local health check services that sit behind reverse proxies.

**Comment by radusuciu** [comment]
Recently hit this issue as well. Are there any security implications with setting this header to `0.0.0.0` as default if that header is not set?

**Comment by steverecio** [comment]
@radusuciu we could make it default to `None` instead of `0.0.0.0` (the audit log models have nullable `remote_ip` fields)

**Comment by radusuciu** [comment]
> @radusuciu we could make it default to `None` instead of `0.0.0.0` (the audit log models have nullable `remote_ip` fields)

That sounds way safer!
