### ISSUE TITLE
unique together index

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#17]
Would you be interested in offering a unique_together index on (`object_id` and `content_type`)? We have a lot of `CRUDEvent` objects and it would be faster to look those up if we could get it through an index.

I'm open to alternative suggestions, and of course a flat out no is "ok" given that this is a fairly generic library that doesn't intend to be particularly opinionated/obtrusive.

**Comment by soynatan** [comment]
The thing, if I'm not mistaken, is that a `unique_together` index on (`object_id` and `content_type`) would allow us to create just one CRUDEevent object per related object (and it is necessary to log every event on the related object).

Perhaps a better solution would be to use Django's meta option, [`index_together`](https://docs.djangoproject.com/en/1.11/ref/models/options/#index-together), like so:

  ```
  classs Meta:
    index_together = ['object_id', 'content_type']
  ```

Tell me what you think.

**Comment by jheld** [comment]
@soynatan ah yes. Just a typo. Sound reasonable then?

**Comment by soynatan** [comment]
Yes, I think that as the log grows, it can be of value to have an index on those fields. You are welcome to make a pull request, otherwise I'll add it in a few days.
