### ISSUE TITLE
Error when running unit tests

### ISSUE THREAD

**Issue by Th-Havy** [soynatan/django-easy-audit#188]
Hi,

I am setting up unit tests for a new project, and easy audit seems to interfere somehow.

Here is the relevant output when I run `python manage.py test`
```
Creating test database for alias 'default'...
easy audit had a post_save exception on CRUDEvent creation. instance: database_users, instance pk: 1
Traceback (most recent call last):
  File "path\to\my\repo\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "path\to\my\repo\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: easyaudit_crudevent
```

My understanding is that the easyaudit tables are not created yet, but the post_save signals for models are already registered leading to errors.

I was wondering if there was a way to fix (currently I disable easy-audit from my installed_apps) ?

It is worth noting that on the first `migrate` that I run (e.g. I delete the DB) I get some warnings/errors from easyaudit, unless I run first the migrations for easy-audit:
```bash
python manage.py migrate easy-audit
python manage.py migrate
```

Thanks,

TH

**Comment by targetblank** [comment]
One possible solution: Add a dependency to easyaudit in your own migration where the error is thrown:

```
dependencies = [
    ("easyaudit", "__latest__"),
]
```

**Comment by Th-Havy** [comment]
Hello,

Sorry for the late reply. The fix proposed by @targetblank works nicely, I added this dependency in my initial migrations.

Thanks,

TH
