### ISSUE TITLE
Django 3.2/4.0 compatibility

### ISSUE THREAD

**Issue by MaehMaeh** [soynatan/django-easy-audit#204]
Is there a plan to release a stable release version of the 1.3.2? When rebuilding my software I always have the problem that Esay-Audit (in the last stable version 1.3.0) does not work with Django 3.2.x. Soon I would also like to try Django 4.

**Comment by jheld** [comment]
just released `v1.3.2` stable!

**Comment by MaehMaeh** [comment]
Thanks a lot
