### ISSUE TITLE
Please Upgrade  to django 4.0

### ISSUE THREAD

**Issue by EhsanSafir** [soynatan/django-easy-audit#206]
change 
`from django.utils.translation import ugettext_lazy as _`
to 
`from django.utils.translation import gettext_lazy as _`

and other django 4 new features

**Comment by jheld** [comment]
And other django 4 new features seems vague/abstract. Anything which is explicitly breaking should be fixed -- agreed. Would you mind opening a PR with the proposed fixes?

**Comment by BartKalkman** [comment]
Why is the requirement set to django <= 4.0 This means that django 4.0.1 is not compatible but i think it is right?
