### ISSUE TITLE
Migration missing for field ID

### ISSUE THREAD

**Issue by majikman111** [soynatan/django-easy-audit#214]
Migrations were not included for commit [fd05524dec14316a29191ad3e2934b99ee44843c](https://github.com/soynatan/django-easy-audit/commit/fd05524dec14316a29191ad3e2934b99ee44843c).

Please add the missing migrations so that running "makemigrations" is not required after installing django-easy-audit.

**Comment by jheld** [comment]
Apologies, I'm not sure how easy it will be for me to try reproducing the issue; the commit you reference _does_ have a migration file committed. Can you provide the `makemigrations --dry-run` output you receive?

**Comment by jheld** [comment]
Ok, this is what I was hoping. This is from a behavior change in Django for the big auto field. It's not something that easy audit specifically did on its own. Technically it may be able to be remedied on the application side (by not defaulting to the big auto field), but alas I suspect there is no setting on a per-model basis to accommodate the older field type.

Can you open a PR with the change?

**Comment by jheld** [comment]
https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys ok there are some options available to us.

We can set it per-app or per-model.

For per-model:
```
    id = models.AutoField(primary_key=True)
```

So adding that line on the models easy audit defines would resolve this.

**Comment by majikman111** [comment]
Unfortunately, due to workplace restrictions, I'm limited to submitting bug reports to open source repos and am not allowed to author PRs.

**Comment by jheld** [comment]
Is this dependent on the license?

**Comment by majikman111** [comment]
No, it's just a blanket restriction for any open-source projects.

**Comment by jheld** [comment]
I'm really astounded by your company's policy. That's so backwards. 

Hopefully the project will have a fix in place before too long; it's a good thing that the vast majority of developers are free and encouraged to work on open source.

If your company is in a position to help fund some of this work, we can setup Github Sponsors.

You are welcome to share this post with them.

**Comment by mschoettle** [comment]
I noticed the same issue and might be able to put together a PR. I don't see any contributing instructions. Anything that should be considered?

**Comment by jheld** [comment]
PR against `master` should be fine. With regards to a solution, if you can consider implementing any settings based on the docs link I provided above, that would be beneficial.

I'm not 100% certain that the library should simply update or not update to the big auto field, but short term I think it's fine not to (hence specifying the usual non big auto field).
