### ISSUE TITLE
Related IDs do not work with UUIDs

### ISSUE THREAD

**Issue by MaehMaeh** [soynatan/django-easy-audit#221]
The `m2m_changed` signal method throws an error (`Object of type UUID is not JSON serializable`) if UUIDs are used for the IDs. If the `DjangoJSONEncoder` is used, the error does not occur.

#### signals/model_signals.py
```
object_json_repr = json.dumps(tmp_repr, cls=DjangoJSONEncoder)
```
instead of
```
object_json_repr = json.dumps(tmp_repr)
```

**Comment by jberends** [comment]
We do encounter this same problem as well on our database where we use UUID's as primary keys all over when processing signals asynchronously through celery. Our error logs (to sentry.io) is filling up because of this. Can we put this into a release soon? See #223

**Comment by KaczuH** [comment]
@jheld Thank you for merging it in! :heart: :rocket:
