### ISSUE TITLE
Django versions badge not up to date (part 2)

### ISSUE THREAD

**Issue by Jack-Smallhold** [soynatan/django-easy-audit#230]
Looks like setup.py notes Django 4.0 as a classifier but pypi is not up to date. As such, the badge only goes up to 3.2
Is this acceptable for 4.0?

**Comment by jheld** [comment]
Ah okay I think the reason is because the releases which do support django 4.0 have not made their way as the default PyPI release because they're all alpha/beta. if you're able to help test the most recent release from today, I can make the build officially stable.

**Comment by Jack-Smallhold** [comment]
understood, thank you!
