### ISSUE TITLE
Delta and full update JSON on CRUDEvent

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#24]
My team is considering having a delta field of the changes, as opposed to the full JSON object on `post_save`.

I haven't started my implementation yet, but I was curious what you thought of the following extension:

- In the signal code, let the output of the callback/hook code (as we know, it's optional), return False, or True, or some sort of enum-like value. In this case it could be FULL, DELTA. That could be a little confusing, but maybe not so bad. Or, have it be a different kind of hook -- different from the one currently implemented in the code.

- Allow saving both the FULL and DELTA on the CRUDEvent, so the project can determine if they want both or one or the other, always, or programmatically. This is in the same vein as above. It unfortunately would potentially duplicate the JSON in the worst case, if both are used on a given object operation.

I want to keep it as simple as possible, but still flexible for the consumer's needs. Are you interested in such a change?

**Comment by soynatan** [comment]
I am interested in this. Now, instead of using a setting or callback to modify this behaviour, what do you think about having two separate fields on the CRUDEvent model out of the box? One for the full state of the object and the other for the delta update. Would it have any drawbacks? Maybe you already thought about this and determined it wouldn't be a good idea.

**Comment by jheld** [comment]
@soynatan I do think it would be nice to be able to have them both in there, as you say.

I am a little concerned that if all or most fields are updated on a given operation that we'd be storing the JSON twice. From a storage perspective, I'm not too happy with that. Using a `null` or `''` could be a solution to this, a marker to tell the consumer that they should look at the full object. Either that, or we `null` or `''` the `object_json_repr` in favor of just showing the delta, in the case where it's all fields that were changed. And by all fields, I mean all fields in the new repr are either not present in the first (if exists), or are different than the old.

If you don't think we should be concerned about double storage, then I don't mind either. And we could make that a settings flag `EASY_AUDIT_NULL_FULL_ON_FULL_DELTA` or something like that.

For the delta, we should probably just stick with showing the mutated (added or changed) fields. 

The alternative is a larger JSON for `{'added': {field_x: value_x, }, 'modified': {field_x: value_x}, 'deleted': {field_x: value_x}}`. It would be a decent interface, but I think it would only end up being a top-level check, so if one of the values itself was a JSONField, you'd get a huge blob with only a small thing inside ti changed.

So, yeah, I vote for the delta just being the `{field_x: value_x}` JSON and the user can piece the chain together as they wish.

**Comment by soynatan** [comment]
Great! I like the idea of logging only the mutated fields with a `{field_a: value_a, field_b: value_b,}` format. I also wouldn't worry about adding a setting to control what to do when all the fields are updated at once. Perhaps in the future if we find it necessary.

I will create a branch for this feature, to which you can merge when you have something on this. Thank you!

**Comment by novarac23** [comment]
@soynatan @jheld I wrote a little something that will give us `{'field_name: (prev_state, after_state)}` https://github.com/soynatan/django-easy-audit/pull/48

Let me know what you guys thing!

**Comment by jheld** [comment]
Hi @novarac23 I appreciate you taking the initiative. I let the ball drop on this one; thank you!

One thing I'm not sure about is the prev_state to after_state. This is because if there is a model change, there wouldn't be a prev_state and it would look confusing (especially if `None` really could be a valid prev_state).

But, I can see how I'd be wrong about that! `None` could be fine/valid. Also, if a field is removed, that has an issue, too. Perhaps removal just won't be part of the structure.

So, if nothing changes on `field_x`, then `field_x` won't be in the update structure, right?

I'll try to look at the code soon.

**Comment by novarac23** [comment]
@jheld Hi! 

Thank you for raising the issue at the first place! I likely wouldn't taken the initiative if it wasn't the issue for someone else except me :)

As far as tracking `None` or `""` as a state I think I like that. For example if you want to build an app  ( like an ember/angular/react/mobile ) that is an activity logger of a sort, knowing when things changed to "nothing" becomes useful. Based on the logs we could show something like this to the user `John just changed their blog post title from "Hunting Lions" to nothing`. Not sure if this makes sense?

Yes if nothing changes `field_x` should not update the structure. Also if it an object is being created `changed_fields` will be empty. Same goes for deleting an object.

Excited to merge this 💪
