### ISSUE TITLE
Does not work with Django version 5 or higher

### ISSUE THREAD

**Issue by klajdicaushi** [soynatan/django-easy-audit#275]
If the project uses Django 5 or higher, when trying to install the library, an error is raised, indicating that the library requests django <5.0.
Is there any particular reason that Django 5 is not supported or perhaps the dependencies should simply be updated?

**Comment by mschoettle** [comment]
This has been fixed already in #265. Unfortunately it’s not released yet. However, there is an alpha release which contains the fix: https://github.com/soynatan/django-easy-audit/releases/tag/v1.3.6.a2

@jheld may be able to tell when this will be fully released

**Comment by jheld** [comment]
Just cut the 1.3.6 release, thank you all!

**Comment by klajdicaushi** [comment]
That's great, thank you both for the quick feedback!
