### ISSUE TITLE
Error Deleting a model on django 1.11.3

### ISSUE THREAD

**Issue by ajd394** [soynatan/django-easy-audit#30]
> Traceback:  
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/core/handlers/exception.py" in inner
>   41.             response = get_response(request)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
>   249.             response = self._get_response(request)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/core/handlers/base.py" in _get_response
>   187.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/core/handlers/base.py" in _get_response
>   185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/views/decorators/csrf.py" in wrapped_view
>   58.         return view_func(*args, **kwargs)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/rest_framework/viewsets.py" in view
>   86.             return self.dispatch(request, *args, **kwargs)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/rest_framework/views.py" in dispatch
>   489.             response = self.handle_exception(exc)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/rest_framework/views.py" in handle_exception
>   449.             self.raise_uncaught_exception(exc)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/rest_framework/views.py" in dispatch
>   486.             response = handler(request, *args, **kwargs)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/rest_framework/mixins.py" in destroy
>   93.         self.perform_destroy(instance)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/rest_framework/mixins.py" in perform_destroy
>   97.         instance.delete()
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/models/base.py" in delete
>   973.         return collector.delete()
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/models/deletion.py" in delete
>   302.                 count = query.delete_batch(pk_list, self.using)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/models/sql/subqueries.py" in delete_batch
>   45.             num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/models/sql/subqueries.py" in do_query
>   28.         cursor = self.get_compiler(using).execute_sql(CURSOR)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/models/sql/compiler.py" in execute_sql
>   886.             raise original_exception
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/models/sql/compiler.py" in execute_sql
>   876.             cursor.execute(sql, params)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/backends/utils.py" in execute
>   80.             return super(CursorDebugWrapper, self).execute(sql, params)
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/backends/utils.py" in execute
>   60.         self.db.validate_no_broken_transaction()
> 
> File "/opt/<redacted>/env/<redacted>/lib64/python3.5/site-packages/django/db/backends/base/base.py" in validate_no_broken_transaction
>   448.                 "An error occurred in the current transaction. You can't "
> 
> Exception Type: TransactionManagementError at /api/v1/media/c807c0dd-d312-4d4f-b151-8d7f0d45b529/
> Exception Value: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

**Comment by jheld** [comment]
Curious, have you been able to determine the specific point of failure?

**Comment by ajd394** [comment]
@jheld I have not had time to do a proper bug hunt (and probably wont in the near future) . All i know for sure is if i take easy audit out of the django settings file my app works and it doesn't work if its in. I know its not very helpful but I thought id put it up here in case anyone else had come across this.

**Comment by jheld** [comment]
@ajd394 no worries. Can you provide system level info? Your database type & version, your python version? Do all deletes fail, or just a certain type of model?

**Comment by ajd394** [comment]
@jheld

OS: Centos 7.3 
Database: Postgres 9.6
Python: 3.5

As far as i could tell all deletes were failing but I did not do an exhaustive test.

**Comment by soynatan** [comment]
All I can tell you is that after installing easy-audit to your project (that is, adding it to your `INSTALLED_APPS` and `MIDDLEWARE` settings) it is necessary to migrate it (`python manage.py migrate easyaudit`). If you don't run the migrations, whenever you try to create, update or delete an entry, you will get an exception like the one you got:

    An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

So, maybe you forgot to run migrations?

I'm closing this issue as we don't have much more info to work on. But thank you for your input, and you're welcome to report any problem you have with the app.
