### ISSUE TITLE
Readonly events

### ISSUE THREAD

**Issue by xkill** [soynatan/django-easy-audit#31]
The events should be readonly by default.

**Comment by soynatan** [comment]
I'm working on this. Problem is, even if all fields are readonly, events can still be deleted or added by hand. And, if those permissions (add, change, delete) are removed, the model simply won't appear in the admin. That's how the Django admin works.

So, maybe we can make all fields readonly by default, but from a security point of view, that won't help much.

**Comment by jheld** [comment]
@soynatan another way of looking at this could be letting the project itself determine who should have access to modifying (deleting) these.

For instance, the consumer's project could say only `is_superuser` users can perform all operations on this admin class.

It's easy to subclass and re-register library admin classes.

**Comment by soynatan** [comment]
@jheld, I agree. As it is now, all operations can be restricted using Django admin permissions. However, if you want to add another layer of security, we can provide a setting to avoid Easy Audit registering the models in the admin site. Then, in your project you can register Easy Audit models yourself, using whatever security checks you want in `ModelAdmin` classes.

What I'm not sure about is whether it is necessary to provide a setting to tell Easy Audit not register the models in the admin site. Maybe the consumer's project can unregister or re-register them.

**Comment by soynatan** [comment]
I just [committed](https://github.com/soynatan/django-easy-audit/commit/39fe96cc4862a130fe4c4ef181ffbd4283079fc9). There are three new settings:

* `DJANGO_EASY_AUDIT_ADMIN_SHOW_MODEL_EVENTS`

* `DJANGO_EASY_AUDIT_ADMIN_SHOW_AUTH_EVENTS`

* `DJANGO_EASY_AUDIT_ADMIN_SHOW_REQUEST_EVENTS`

They allow you to show models in the admin or not. They're all `True` by default.

If you want to make fields readonly, add security checks in the admin, or simply not allow any user to create, change, or delete entries, then these settings can come handy, as they allow you to register Easy Audit models in the admin in whatever way you want, using `ModelAdmin`.
