### ISSUE TITLE
request signal cookie py3

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#35]
Looks like we have a python3 incompatibility in the request signals module.

It does `from Cookie mport SimpleCookie`.

It looks like the module in py3 is: `http.cookies.SimpleCookie`

If using `six` it could be `six.moves.http_cookies.SimpleCookie`. Or we could just do an import try/except.

**Comment by soynatan** [comment]
Great. Can't we do something like this?:

```
from django.utils import six

if six.PY2:
    from Cookie import SimpleCookie
else:
    from http.cookies import SimpleCookie
```

**Comment by jheld** [comment]
@soynatan thanks for the quick turnaround. When might you release a new version to PyPI? I'm unsure when I'll be working on the delta/change set for CRUDEvent.

**Comment by soynatan** [comment]
No problem. I'll make a new release to PyPi after I close #31, which I'll try to do today.
