### ISSUE TITLE
it would be nice to config what entities should be audited to avoid ALL by default

### ISSUE THREAD

**Issue by dmitry-saritasa** [soynatan/django-easy-audit#5]

**Comment by dmitry-saritasa** [comment]
for example through a decorator against Model class

**Comment by soynatan** [comment]
Right now, the app audits everything, except the models specified in: `DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_DEFAULT` and `DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA`. This is explained [here](https://github.com/soynatan/django-easy-audit#settings).

If I understand you correctly, what you suggest is a way to **avoid auditing everything by default**, except some specific models. I think it could be useful.

**Comment by dmitry-saritasa** [comment]
> If I understand you correctly, what you suggest is a way to avoid auditing everything by default, except some specific models. I think it could be useful.

yes, exactly

**Comment by soynatan** [comment]
This has been solved by adding another setting, in #15. The app will only log the models listed in `DJANGO_EASY_AUDIT_REGISTERED_CLASSES`. If any of the models in this setting is also listed in the unregistered classes settings, it won't be logged. 

You can check it out and are welcome to open another issue if you find a problem with it. Thanks!
