### ISSUE TITLE
Data too long for column 'query_string'

### ISSUE THREAD

**Issue by dapicester** [soynatan/django-easy-audit#50]
Hi, I am using Django 1.10.7 with MySQL 5.7 and one of my test failed with the following error:
```
DataError: (1406, "Data too long for column 'query_string' at row 1")
```
The test is sending a GET request to one of my API endpoint with a fairly large query string.
So I checked the [RequestEvent](https://github.com/soynatan/django-easy-audit/blob/master/easyaudit/models.py#L72) model and indeed the `query_string` attribute has a `max_length=255`.

After a quick search I found out on [this StackOverflow question](https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string) that the actual maximum length of the query string may be bigger. I wonder if it is appropriate to either use a larger `max_length` (e.g. 4000) or use a `TextField` for storing the query string.

**Comment by jheld** [comment]
hi @dapicester sorry for the delay. This is definitely a bug as we've seen. One way around it until we issue a db migration is to add that URL to `DJANGO_EASY_AUDIT_UNREGISTERED_URLS_DEFAULT` in your `settings.py`.

If that isn't reasonable, then we'll try to prioritize the fix faster. It really shouldn't be a hard fix for us, though!

**Comment by soynatan** [comment]
This was just fixed [here](https://github.com/soynatan/django-easy-audit/commit/3518a7b3d6225f6b0340c920ebedfad9490eafe1). Thank you!
