### ISSUE TITLE
Make the app thread safe

### ISSUE THREAD

**Issue by soynatan** [soynatan/django-easy-audit#6]
From u/boxidea in r/django:

> I don't think that storing the request on the EasyAuditMiddleware class is a good idea.
>
> Middleware classes are shared across requests, so anything you store on the class is not going to be thread safe.

https://www.reddit.com/r/django/comments/5ux246/hello_everyone_i_created_a_simple_django_app_to/ddxpw8n/

**Comment by jheld** [comment]
@soynatan any update on this?

**Comment by soynatan** [comment]
No, I haven't had any time to check this. I opened the issue so I wouldn't forget about it. If you want to try [this fix](http://stackoverflow.com/questions/3227180/why-is-using-thread-locals-in-django-bad/39313777#39313777) go ahead, otherwise I'll do it in a couple of days.

**Comment by soynatan** [comment]
I applied the fix. Seems to be working ok. We'll open another issue if it causes any problem.
