### ISSUE TITLE
CRUDEvent.object_repr field too small

### ISSUE THREAD

**Issue by worsht** [soynatan/django-easy-audit#60]
`CRUDEvent.obj_repr` is defined as a `CharField(max_length=255)`. There are valid reasons to have `repr`s longer than 255 chars. I suggest changing this to `models.TextField(null=True, blank=True)`.

**Comment by vcostas** [comment]
Hi, why do not you use a json data type?

**Comment by jheld** [comment]
@vcostas it's a good question. Unfortunately at least for MySQL we cannot guarantee that the version used supports it.
