### ISSUE TITLE
removal of db_constraint on User

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#71]
Hello!

My project was/is looking to separate our easyaudit data to a separate database.

What would your thoughts be on removing the db_constraint on the models that reference a User?

This would mean that if the User doesn't exist that an exception would be raised when trying to access it.

However under normal flow it would be fine for most applications.

I'm not sure if there are other side effects from doing this, but I wanted your thoughts. I'm also not sure that this could be a project-level setting (as in it may have to be hard-coded).

**Comment by jheld** [comment]
My team will be looking into this in the short term. We're going to find out how feasible it is and what changes are needed in this project to accommodate it.

**Comment by soynatan** [comment]
Hello, sorry, I haven't been able to work on easy audit. I still need to close another project before I can get my hands on this. If you and your team will be working on this, that would be great to know the implications. Thank you.

**Comment by soynatan** [comment]
Closing as it has been implemented in #80. Thank you for your work.
