### ISSUE TITLE
TransactionManagementError 

### ISSUE THREAD

**Issue by sa9** [soynatan/django-easy-audit#73]
easy_audit has been working flawlessly for over a year but lately, I am having a similar issue to this one:

https://github.com/encode/django-rest-framework/issues/5859

I couldn't find the root cause exactly but I can confirm that removing easy_audit from the INSTALLED_APPS solved this issue.  

I wonder if there are instructions on how to uninstall easy-audit and all related tables cleanly?

**Comment by jheld** [comment]
Would you be able to provide any further details about the runtime error? Is this something you could run in a debug mode with a breakpoint?

What version of the project are you running? Which database? Django version, etc.

**Comment by sa9** [comment]
I am using django=2.0.8 , django-easy-audit==1.0 with Postgres 9.5

The issue started in django's dbshell when I made an error in one statement syntax (to reset id sequence in one of the models) and I exited the dbshell without performing a rollback (it didn't occur to me to do it). It turns out Postgres doesn't do rollback automatically in dbshell (see this ticket https://code.djangoproject.com/ticket/10813). After that, I start to get the following error whenever I add a new record to any model my app:

`django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.`

I tried to do rollback again in a new dbshell session and also from pgAdmin but theTransactionManagementError persisted. I tried a debug mode with a breakpoint at various part of the error trace but I couldn't find anything meaningful. Unfortunately, I can't reproduce the error now after removing easy-audit and fixing the database.

**Comment by morlandi** [comment]
You could try to turn on database level autocommit by adding:

```
'OPTIONS': {'autocommit': True,}
````

to database settings; this sometimes reveales the hidden db exception

**Comment by sa9** [comment]
@morlandi 
Agree. This also would make dbshell / Postgres more resilient to errors too.

**Comment by soynatan** [comment]
@sa9
 
> I can confirm that removing easy_audit from the INSTALLED_APPS solved this issue
> I can't reproduce the error now after removing easy-audit and fixing the database.

I'm closing this issue as the problem has been solved, and there seems to be solution, which is not great, but we'll leave it for now.
