### ISSUE TITLE
How do I create new migrations in this project?

### ISSUE THREAD

**Issue by dopatraman** [soynatan/django-easy-audit#83]
Most django projects have a `manage.py` file that gives access to `makemigrations`. This project does not have one, yet I see programmatically generated migration files. More out of curiosity than anything else, how did @soynatan create them?

**Comment by jheld** [comment]
One way I have is by using the test project. But you can do it against your existing project, too, because it registers the models.

**Comment by dopatraman** [comment]
@jheld sorry, I don't follow. Wouldn't running migrations in the test project only create migrations for test models?

**Comment by soynatan** [comment]
Are you using Linux? If so, you can clone this repo, and then, in the root of your django project add a symbolic link to the folder "easyaudit". Then, you can work on the repo and test it in your project. You can then use your project's manage.py to create migrations.

**Comment by dopatraman** [comment]
@soynatan I see, thanks for the advice. Just out of curiosity, was there a reason the manage.py file was removed from the project? I'm not sure I understand the benefits of not having it.

**Comment by soynatan** [comment]
manage.py wasn't removed, because it was never there. This repo contains a django app, not a django project.

> [...] when you run `django-admin startproject mysite` you’ll get a `mysite` project directory that contains a `mysite` Python package with `settings.py`, `urls.py`, and `wsgi.py` [...]
>
> A project’s root directory (the one that contains `manage.py`) is usually the container for all of a project’s applications [...]
>
> The term application describes a Python package that provides some set of features. Applications may be reused in various projects.
>
> Applications include some combination of models, views, templates, template tags, static files, URLs, middleware, etc. They’re generally wired into projects with the `INSTALLED_APPS` setting and optionally with other mechanisms such as URLconfs, the `MIDDLEWARE` setting, or template inheritance.

[See more about the difference between a projects and apps](https://docs.djangoproject.com/en/2.1/ref/applications/#projects-and-applications).

**Comment by dopatraman** [comment]
How were the original migrations created?

**Comment by morlandi** [comment]
> How were the original migrations created?

Just run 

`python manage.py makemigrations APPNAME`

from the main project.

The new migrations will be created in the app folder.
If it's in site-packages of your virtualenv, it's useless and probably harmfull.
If however you a have a working clone of the the app, then this is what you want ... and from there you can later commit the changes

**Comment by morlandi** [comment]
> Are you using Linux? If so, you can clone this repo, and then, in the root of your django project add a symbolic link to the folder "easyaudit". 

This certainly works on Linux.
If you're using pip, there is another option.
With the virtualenv of your main project activated, run:

`pip install -e <PATH_TO_APP_FOLDER>`

where <PATH_TO_APP_FOLDER> is where your local working copy of the app lives; "-e" stands for "editable".

Later, when you have committed the changes to the app - and hopefully created a PR to the main repo ;) - you can restore a clean environment by "pip-uninstalling" the local copy of the app, and reinstall it as usual with "pip install" form either your github fork, of from Pypi in case a new app release has been created to include your changes
