### ISSUE TITLE
`user` field in CRUDEvent should be SET_NULL again

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#9]
Turns out my change to allow the `CRUDEvent` to `DO_NOTHING` on a user deletion was a mistake (in specific circumstances). It means we can't delete the user, due to a referential integrity.

I propose I put it back to `SET_NULL`, **and** I add a new field to the model, maybe `user_id_string`, which will then hold onto the `user` pk/id even after deletion. This is needed because my project needs a full audit history of user information for operations on models, but also needs the ability in certain circumstances to delete said user, while not losing the audit history.

I can write this up pretty fast, but wanted your input, first.

**Comment by soynatan** [comment]
Interesting, I guess I never deleted a user while testing the app. Go ahead with this!

I only have one question: the field `user_id_string`, is it a string because the user model could have a CharField as a primary key? Or am I missing something?

Thank you.
