### ISSUE TITLE
Charfield Primary Key

### ISSUE THREAD

**Issue by steverecio** [soynatan/django-easy-audit#90]
I'm getting a pre-save exception on my models that use a guid charfield as their primary key. This is the line that I believe is causing the issue: https://github.com/soynatan/django-easy-audit/blob/master/easyaudit/signals/model_signals.py#L101

For reference here is a snippet of my model:

```
def _generate_uuid():
    return uuid.uuid4().hex

class SampleModel(models.Model):
    _id = models.CharField(max_length=32, primary_key=True, editable=False, default=_generate_uuid)
```

**Comment by steverecio** [comment]
This can be fixed by changing the object_id on `CRUDEvent` to a CharField: https://github.com/soynatan/django-easy-audit/blob/03e05bc94beb29fc3e4ff86e313a6fef4b766b4b/easyaudit/models.py#L23

See the "Primary key type compatibility" section here: https://docs.djangoproject.com/en/2.2/ref/contrib/contenttypes/#generic-relations

**Comment by jheld** [comment]
We have been hesitant to change to a generic relation. Set null, do nothing semantics etc for deletion.

However yes changing to charfield has been a consideration.

Moving to a charfield should work ok. I think django will auto type convert str IDs to int and vice versa (look ups in either direction).
