### ISSUE TITLE
Project settings import

### ISSUE THREAD

**Issue by Marpop** [soynatan/django-easy-audit#91]
Hey, thanks for the library ;)

I have an issue with settings. It seems django-easy-audit didn't see setting from https://github.com/soynatan/django-easy-audit/wiki/Settings.

I have multiple settings files (in config/settings/ dir), but I think it isn't a problem because it works with other 3rd party libraries. 

Here is my config:

```
# Django Easy Audit
# ------------------------------------------------------------------------------
# https://github.com/soynatan/django-easy-audit/wiki/Settings
DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS = False
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False
```

**Comment by jheld** [comment]
Is this still an issue? Can you provide other details if you've investigated further? Also, which version of django, easy audit, and python?

**Comment by Marpop** [comment]
Hey, everyting is OK now. I was thinking that for example `DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False`
will hide `Request events` from admin. I suppose that is expected behaviour. 
![image](https://user-images.githubusercontent.com/15074433/62527581-ae65d000-b83b-11e9-8d2c-9211879d1858.png)
