### ISSUE TITLE
Can I set RequestEventid as foreign key to CRUDEvent? 

### ISSUE THREAD

**Issue by Itspritish3** [soynatan/django-easy-audit#96]
Can I set RequestEventid as foreign key to CRUDEvent? 
i am not able to figure out how can i get RequestEventid  while saving  CRUDEvent in database.
help..

**Comment by jheld** [comment]
So your goal is to link certain CRUDEvent instances to a given RequestEvent?

We have been wondering the same.

RequestEvent uses the django middleware signals, and CRUDEvent uses the model signals.

Potentially you could do fuzzy logic to find all CRUDEvent against that user in the time-frame of the request, but that still isn't perfect, especially if you have concurrent API access by that user on other API calls in the same time frame.

Am I complicating your request? Again, we've wondered the same.

**Comment by jheld** [comment]
Closing for now. Please re-open if you would like more help or if you would like to discuss a solution.
